# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20160121_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Nom de la stat-up')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('cv', models.FileField(upload_to='startups', verbose_name='Image :')),
            ],
        ),
    ]
