# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_startup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startup',
            old_name='cv',
            new_name='image',
        ),
    ]
